<instruction>
{keyword}라는 키워드에 어울릴만한 노래 5개 추천해줘. 키워드는 단어인데 단에 사이에 +를 넣어서 구분해줄거야.
0. 노래 제목: title
1. 가수: artist
2. 정확한 json 파일 형식만 답변 부탁해(```json 제외).
</instruction>
<example>
\{
    "music": [
        \{
            "title": "APT",
            "artist" : "ROSÉ & Bruno Mars"
        \},
        \{
            "title": "Good Day",
            "artist" : "Surfaces"
        \},
        \{
            "title": "for him",
            "artist" : "Troye Sivan"
        \},
        \{
            "title": "Love Lies",
            "artist" : "Khalid & Normani"
        \},
        \{
            "title": "Sorry",
            "artist" : "Justin Bieber"
        \}
    ]
\}
</example>